name: GitHub Actions Test 22
on: [push]
jobs:
  run-22-09:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x.x
          cache: npm
          cache-dependency-path: "./22/09/package-lock.json"
      - name: Install modules
        run: npm install
        working-directory: ./22/09
      - name: Run tests
        run: ./node_modules/mocha/bin/mocha.js .
        working-directory: ./22/09
