name: GitHub Actions Test 22
on: [push]
jobs:
  run-22-09:
    runs-on: self-hosted
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x.x
          cache: npm
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install modules
        run: cd ./22/09/ && npm install
      - name: Run tests
        run: cd ./22/09/ && ./node_modules/mocha/bin/mocha.js .
